struct flow{ 
         struct flow_tnl tunnel;
         ovs_be64 metadata;
         uint32_t regs[FLOW_N_REGS];
         uint32_t skb_priority;
         uint32_t pkt_mark;
         uint32_t dp_hash;

         union flow_in_port in_port;
         uint32_t recirc_id;
         uint8_t ct_state;
         uint8_t ct_nw_proto;
         uint16_t ct_zone;
         uint32_t ct_mark;
         ovs_be32 packet_type;
         ovs_u128 ct_label;
         uint32_t conj_id;
         ofp_port_t actset_output; 
     struct eth_addr dl_dst; 
     struct eth_addr dl_src;
     ovs_be16 dl_type;
     uint8_t pad1[2];
     ovs_be32  ip2_dst;
     ovs_be32  ip2_src;
     uint8_t  ip2_info1;
     uint8_t  ip2_type;
     ovs_be16  ip2_info2;
     struct  stip2_info3  ip2_info3;
     uint8_t pad4;
     ovs_be16  ip3_dst;
     ovs_be16  ip3_src;
     uint8_t  ip3_info1;
     uint8_t  ip3_info2;
     ovs_be16  ip3_type;
     ovs_be16  tp1_dst;
     ovs_be16  tp1_src;
     ovs_be16  tp1_info2;
     ovs_be16  tp1_type;
     uint8_t  tp1_info1;
     uint8_t pad5[7];
     uint8_t  tp2_dst;
     uint8_t  tp2_src;
     ovs_be16  tp2_info2;
     ovs_be32  tp2_info1;
     ovs_be16  tp2_type;
     uint8_t pad6[6];
};
